### ISSUE TITLE
Installation on develop

### ISSUE THREAD

**Issue by GuillaumeGen** [Deducteam/Dedukti#11]
The installation is quite hard to understand, and not at all documented (by reading the .travis.ml, we get some information, but reading the Readme is the normal choice):
 - "oasis setup" raises "W: No exported module defined for library dedukti", but we are suppose to guess that it works
 - "./configure --enable-tests" Would be great to be able to set in which folder the program will be installed (I know that I must set prefix in setup.data, but that's not a common knowledge)
 - "make build" works as expected
 - "make test" does a build again (I don't like this, but this was the previous behaviour on develop, not the behaviour on master).

Furthermore, there is no Makefile anymore, meaning that doing a checkouts between master and develop destroy the Makefile, meaning, that we must redo our changes in setup.data each time, that's a bit boring.

**Comment by rlepigre** [comment]
My opinion is that we should move back to a more standard build system (combination of ocamlbuild, ocamldep and GNU make), which would be a lot easier to maintain and understand. If everyone agrees, I can make the change since I'm used to these stuff.

**Comment by francoisthire** [comment]
>
> The installation is quite hard to understand, and not at all documented
> (by reading the .travis.ml, we get some information, but reading the
> Readme is the normal choice)
>
 First of all, the installation is this one since august now. Except I
removed the usual files for the develop branch. BUT, if we move on master,
we should keep the generated files (configure and Makefile). Oasis is
helpful only for the develop branch. But you are write it should be
documented.

>
>    - "oasis setup" raises "W: No exported module defined for library
>    dedukti", but we are suppose to guess that it works
>
> Yeah, I should fix that. But the warning is not important. It says that
the libraries built are

Dedukti.kernel
Dedukti.parser

but Dedukti alone does not have any module.

>
>    - "./configure --enable-tests" Would be great to be able to set in
>    which folder the program will be installed (I know that I must set prefix
>    in setup.data, but that's not a common knowledge)
>
> Well, I think it is possible to change directly the _oasis file for that.

>
>    - "make build" works as expected
>    - "make test" does a build again (I don't like this, but this was the
>    previous behaviour on develop, not the behaviour on master).
>
> Are you sure about this? In general it is just a check, as usual with
ocamlbuild.

> Furthermore, there is no Makefile anymore, meaning that doing a checkouts
> between master and develop destroy the Makefile, meaning, that we must redo
> our changes in setup.data each time, that's a bit boring.
>
So only setup.ml has to be exported. setup.data is a generated file by
_oasis that keeps metadata. As I said, once we decide to make a release of
Dedukti, we keep the generated Makefile on Master because people that will
fork the project don't care about generating META files etc...

My opinion is that we should move back to a more standard build system
> (combination of ocamlbuild, ocamldep and GNU make), which would be a lot
> easier to maintain and understand. If everyone agrees, I can make the
> change since I'm used to these stuff.
>

Oasis is very standard in the OCaml world, maybe not for you though. The
problem with your built system is that you need to write the META files,
that is something boring that I don't want to do. Especially that we are
three on the project, I suspect that people will add/remove modules in the
next few months.

And I am not agree with you when you say it is "easier" to maintain or
understand. With _oasis, if you add/remove a module, you have only one line
to change in the _oasis file. I am not sure that it is the case with your
build system. Actually, _oasis was here since a few months now, and no one
cared before I remove the generated files in the develop branch. I realized
it was a problem with Gaspard PR.

The other standard build system is jbuilder (
https://github.com/janestreet/jbuilder), in my opinion this one is also a
good alternative. But the one you propose Rodolphe is, in my opinion too
old and not automatic enough to generated ocamlfind files.

So except the documentation, what is the real issue here?

2017-12-07 13:27 GMT+01:00 Rodolphe Lepigre <notifications@github.com>:

**Comment by GuillaumeGen** [comment]
> First of all, the installation is this one since august now. 
Not at all, until yesterday, make was sufficient to do the compilation. (eventually followed by make install if you want the installation after)

> Are you sure about this?
About what ? In develop make test call make build, not in master.

> So only setup.ml has to be exported. setup.data is a generated file by _oasis that keeps metadata. 
> As I said, once we decide to make a release of Dedukti, we keep the generated Makefile on Master because people that will fork the project don't care about generating META files etc...
But the only people who might use develop are us and we very often checkout between branches, hence, not modifying Makefile or setup.data each time would be great.

**Comment by GuillaumeGen** [comment]
> Actually, _oasis was here since a few months now, and no one cared before

Of course, I cared before, since creating a new command was easy with the master Makefile and I don't know out to do it using oasis (but that's probably more a knowledge problem than a build system problem)

**Comment by francoisthire** [comment]
>
>  >First of all, the installation is this one since august now.
> Not at all, until yesterday, make was sufficient to do the compilation.
> (eventually followed by make install if you want the installation after)
>
As I said, the build system is the same without the generated files.

Are you sure about this?
> About what ? In develop make test call make build, not in master.


About make test does not build again the project, it checks if it has been
build.

>
>
> > So only setup.ml has to be exported. setup.data is a generated file by
> _oasis that keeps metadata.
> > As I said, once we decide to make a release of Dedukti, we keep the
> generated Makefile on Master because people that will fork the project
> don't care about generating META files etc...
> But the only people who might use develop are us and we very often
> checkout between branches, hence, not modifying Makefile or setup.data each
> time would be great.


What is the problem? That instead of make, you have to do oasis setup &&
./configure && make? If you prefer, I can create a script install.sh for
that. Actually, it is great that oasis generates the Makefile for you if in
your project you add modules. Or for example, if you add a binary. So
between two branches, the setup.data might be different. Actually, we can
put the Makefile on git, but setup.data is a bad idea for the develop
branch I think.

Also, the idea that Dedukti's kernel is a library is to avoid having dozens
of branches in the repository. Because most of the time, we don't need to
fork the project, only to use it as a library.

2017-12-07 17:02 GMT+01:00 GuillaumeGen <notifications@github.com>:

**Comment by francoisthire** [comment]
And if you look at the setup.data, there are things that depend on the
system such as:

ocamlfind="/home/fthire/.opam/4.04.2/bin/ocamlfind"
ocamlc="/home/fthire/.opam/4.04.2/bin/ocamlc.opt"
ocamlopt="/home/fthire/.opam/4.04.2/bin/ocamlopt.opt"
ocamlbuild="/home/fthire/.opam/4.04.2/bin/ocamlbuild"

So it is a really bad idea to put on git that kind of file.

2017-12-07 17:23 GMT+01:00 François Thiré <franth2@gmail.com>:

**Comment by Gbury** [comment]
Personnally I dislike oasis:
- First replacing `make` by `oasis setup && ./configure && make` is quite bothersome because it is significantly longer to type, and more importantly to execute, which is problematic since it kinda breaks incremental builds. In theory, as long as you don't change the dependencies or module list, a simple `make` should suffice, but then you forget to re-run the whole command when you add some.
- Generated files tend to be annoying and are commited every so often (even though they shouldn't).
- It make releases painful (because there you have to include at least part of the generated files (i.e the configure script, but not the ` setup.data`))
- oasis in itself is quite a pain to install (even with opam) because of all its dependencies
- I think oasis is way overkill (in terms of complexity) for a single lib with a few executables.

So +1 for switching to ocamlbuild or jbuilder.

**Comment by francoisthire** [comment]
>
> Personnally I dislike oasis:
>
>    - First replacing make by oasis setup && ./configure && make is quite
>    bothersome because it is significantly longer to type, and more importantly
>    to execute, which is problematic since it kinda breaks incremental builds.
>    In theory, as long as you don't change the dependencies or module list, a
>    simple make should suffice, but then you forget to re-run the whole
>    command when you add some.
>
> If we add the Makefile and setup.ml files to the project, then make is
enough. Maybe I should add again Makefile and setup.ml then.

>
>    - Generated files tend to be annoying and are commited every so often
>    (even though they shouldn't).
>
> Well, .gitignore is here to help us.

>
>    - It make releases painful (because there you have to include at least
>    part of the generated files (i.e the configure script, but not the
>    setup.data))
>
> Yeah but it is a trade-off. With oasis adding or removing a module is
easy. Btw, the release problem concerns only one people in the development
team.

>
>    - oasis in itself is quite a pain to install (even with opam) because
>    of all its dependencies
>
> That is something you do it only once every new release of OCaml, and only
if you are a developer of Dedukti...

>
>    - I think oasis is way overkill (in terms of complexity) for a single
>    lib with a few executables.
>
> Actually, there are two libraries (if we take into account the parser). I
do not agree on that point.

> So +1 for switching to ocamlbuild or jbuilder.
>

Why is jbuilder is better according to you? As a developer of Dedukti, I
found oasis very handful when I had to add modules/executable in the
project. Only one file to change, and everything was generated for me. With
the old build system with only Ocamlbuild, it was a bit painful to do that.

2017-12-07 17:36 GMT+01:00 Guillaume Bury <notifications@github.com>:

**Comment by Gbury** [comment]
So:
- About adding Makefile and setup.ml: that's kind of the pain point, because every time someone adds a module, these two file should be updated, and when working on other projects I found that comiting these files often proved to be a mistake because it would break other people's build.
- With ocamlbuild, adding or removing a module is simply a matter of editing the package.mlpack or similar file, i.e you only have to edit one file (by adding/removing a line with the modul name), and you don't have to regenerate a ton of files (same for dependencies, you only have to update the _tags file for it to build again).
- installing oasis is *not* something you do once for every new version of ocaml, since it is recompiled for every update of itself or one of its dependencies (which means actually pretty often given the number of dependencies). And I already have had problems where oasis wouldn't install (for instance on newly released switch).
- jbuilder is lighter, faster, doesn't try and overtake your makefile (which I strongly dislike), and also generates .merlin files. But more importantly, you don't have the whole complex (and error-prone) process of having to run ` oasis setup', then `configure` and then `make`, you only need ` jbuild build`.

Overall, every time I had to work on a project using oasis, it gave me headaches trying to make the project build (I pretty much has to nuke every generated file and re-run the whole process every time i wanted the project to build). On the other hand, ocamlbuild and jbuilder never gave me much trouble (and adding/removing module is as simple as with oasis, I really don't understand why/how you think otherwise).

**Comment by francoisthire** [comment]
> On the other hand, ocamlbuild and jbuilder never gave me much trouble (and adding/removing module is as simple as with oasis, I really don't understand why/how you think otherwise).

It is more about two lines with the mldylib file if you need one. But you are right though. I was mixing two different things. I was also thinking about adding executables or libraries (that might happen in the future if the kernel becomes more generic).

> jbuilder is lighter, faster, doesn't try and overtake your makefile (which I strongly dislike), 

This is also something I prefer. That is why I am actually thinking about moving to JBuilder than going back to Ocamlbuild. Actually, I had a lot of headaches with OCamlbuild too, so I think it is more a personal matter.

Though, even if this discussion is interesting, it is not urgent right? Everything works as expected right now, so maybe it is more a middle term project.

**Comment by rlepigre** [comment]
I mostly agree with @Gbury on what he said  about oasis, but I am not so enthusiastic about jbuilder (maybe because I have never really tried it). However, it seems to be rather similar to oasis, even though it is more trendy...

Anyway, I think that it is important to have a makefile in the repository so that you can compile and install with "make && make install". I also want to be able to type "make distclean" or "make clean" to get rid of all the stuff that should not be here.

**Comment by GuillaumeGen** [comment]
I finally understood why I dislike so much the new settings of oasis.
The files generated by oasis were all tracked by git but setup.data. Hence when checkouting between a branch, it automatically changed all those generated files, now they don't change anymore, meaning that when we have new ml files with a old generated files. Hence of course, it is impossible to make.
You will say to me : "of course, you need to clean your repository before doing a make on a new branch". But make distclean and make clean do not remove any generated files, except setup.data, which is the only one I want to keep. It means that each time I checkout (ie several times a day this week) I have to suppress manually all the generated files, and that's REALLY boring.

**Comment by francoisthire** [comment]
> I finally understood why I dislike so much the new settings of oasis.
The files generated by oasis were all tracked by git but setup.data. Hence when checkouting between a branch, it automatically changed all those generated files. Now they don't change anymore, meaning that we have new ml files with old generated files. Hence of course, it is impossible to make.
You will say to me : "of course, you need to clean your repository before doing a make on a new branch". But make distclean and make clean do not remove any generated files, except setup.data (and _build/ and the .native, but those have no link with oasis), which is the only one I want to keep. It means that each time I checkout (ie several times a day this week) I have to suppress manually all the generated files, and that's REALLY boring.

I don't really understand what you are saying. I never had to suppress manually files with oasis so I suspect you are doing something wrong. Is your complaint about my Wednesday commit or the one from yesterday?

As you, I switch a lot of times between different branches, adding ml files and I never had such problems.
