### ISSUE TITLE
Install binaries in user directory

### ISSUE THREAD

**Issue by rlepigre** [Deducteam/Dedukti#13]
It is currently not possible to just type "make install" in a user session because binaries are always installed system-wide. We should install them in the `$(dir $(shell which ocamlc))` (in makefile language) or somewhere similar.

**Comment by Gbury** [comment]
Doesn't that risk polluting the `.opam` folder ? I mean that it would add files not managed to opam in a folder that is managed by opam, which could potentially cause bugs (for instance when installing/reinstalling dedukti with opam, if files are already present because of a manual installation, I don't know if the default behavior is to overwrite files, or fail, both of which are reasonnable).

More generally, I see two ways of having ocaml isntalled:
- opam, in which case I don't think people should manually install ocaml package. Indeed, opam pinning is a way better option that gives the same results (package is installed, at the correct location) + the package is actually tracked by opam.
- system wide/distribution packages, in which case, your method will fail (since it will not change anything compared to now).

The solution for allowing install from user sessions would be to document the mechanism for choosing the install directory (currently the `INSTALL_DIR` environment variable), or switch to having a `configure` script with a `--prefix` or similar option (which is the usual way afaik).

**Comment by rlepigre** [comment]
There is actually a `bin` directory under each `opam` switch, which purpose is to install binaries. I guess there is no problem doing that, provided that the `uninstall` target of our `opam` configuration also remove these files.

Using `which ocaml` is a reliable way of finding the binary directory where we want things installed, but there might be a better way. Actually, you can also do `There is actually a `bin` directory under each `opam` switch, which purpose is to install binaries. I guess there is no problem doing that, provided that the `uninstall` target of our `opam` configuration also remove these files.

Using `which ocaml` is a reliable way of finding the binary directory where we want things installed, but there might be a better way. Actually, you can also do `opam config var bin` which I just discovered (it might be a recent addition).

**Comment by Gbury** [comment]
Sure, you can hack the build system to install things in the current opam switch, but then the question is: why not use `opam pin`and let opam install it ? It has many advantages:
- no need to re-implement the mechanism for deciding where to install binaries, it is provided by opam
- opam keeps track of installed packages and versions

I really don't see the point of implementing a manual installation process which does exactly the same thing as the normal opam installation, but that doesn't work well with opam...

**Comment by rlepigre** [comment]
The thing is, we want to use `ocamlfind` to install libraries, because that works well. But `ocamlfind` has no support for binaries. Plus, I'm not sure we want to force people into `opam`, or to install anything system-wide. However, what I propose might not be the best solution.

**Comment by Gbury** [comment]
In the case of a non-opam, non-system user installation,I think it's reasonable to require the user to provide explicitly where the binaries should be installed.

**Comment by rlepigre** [comment]
Why ask him/her to do that when a reasonable default choice is available?

**Comment by Gbury** [comment]
Well, let's look at the situations:
- opam is installed: the 'reasonnable' default would be the current switch directory, but I strongly disagree with installing binaries not tracked by opam in this directory, since it can very likely lead to a lots of bugs (mismatch versions between libs, or even switches if one forgets to ` eval $(opam config env)`, untracked files in a package manager direcotries, etc...). Also, if opam is installed, 1) I see no reason not to install dedukti using opam, 2) ocaml packages should definitely not be installed by something else than opam, since it will very likely break as soon as you switch compiler.
- opam is not installed, in that case, in most situations, it means that a system-wide ocaml compiler is installed, in which case either install the package system-wide, or in some user bin directory, such as `$(HOME)/.bin` (or as some suggest `$(HOME)/bin`, but I personally dislike having non-personal non-hidden directories in my home, as it clutters the output of  `ls`), but then, I don't know of a really standard directory for user-specific binaries that everyone agrees on, hence the user-supplied directory.
