### ISSUE TITLE
Having an open command

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/Dedukti#145]
Maybe it would interesting to have an `open` command or at least a renaming command so that terms can be readable even when the name of the module is long.

```
#OPEN md.
(; or ;)
#REQUIRE md AS md.
```

While the renaming command should be easy to implement, I think that `open` might be quite difficult because of the `dko` files.

**Comment by fblanqui** [comment]
This is already implemented in Lambdapi...

Le 23/11/2018 à 16:19, fthire a écrit :

**Comment by francoisthire** [comment]
Yes, but not in Dedukti 2.7 ^^

**Comment by fblanqui** [comment]
What's the point of opening this kind of issue on Dedukti? We agreed 
some time ago that, on Dedukti, there would bug fixes only.

Le 23/11/2018 à 16:31, Frédéric Blanqui a écrit :

**Comment by francoisthire** [comment]
I don't remember that we agreed on that. Instead, we agreed to do a last release of Dedukti based on this version and this is why I am opening this issue since I would like to write a paper with an artifact that would be compatible with this release.

**Comment by fblanqui** [comment]
We agreed not to add new features to Dedukti unless it was really necessary for your work and, even in this case, we said that one should try to submit a PR to Lambdapi for implementing the same feature. Otherwise, it may be never added to Lambdapi. Anyway, why not trying to use Lambdapi instead? Especially while Rodolphe is with us until the end of the year?

**Comment by francoisthire** [comment]
@Gaspi @GuillaumeGen ?

**Comment by francoisthire** [comment]
Not planned.
