### ISSUE TITLE
Dedukti tutorial: Testing by type-checking with a dependent type

### ISSUE THREAD

**Issue by rprimet** [Deducteam/Dedukti#163]
The paragraph 5.4 of the Dedukti tutorial states that:

> Istrue is neither a type like Nat and Bool nor a function, it is a family of types indexed by a boolean; this is called a dependent type.
> 
> There is no term of type Istrue False and tt is the only term of type Istrue True.

For readers who are unfamiliar with proof systems/frameworks, it might be helpful to expand a bit on this statement and to hint at how to check for falseness, i.e. is the fact that there is no term of type `Istrue False` a _requirement_, or is it possible to augment the previous definition with something like

`ff : Istrue False.`

or is it necessary to introduce another dependent type? e.g.

```
Isfalse : Bool -> Type.
ff : Isfalse False.
```
or even something else...

(this may be obvious to more seasoned users though, I'm not sure)

It might also be a good place to introduce the `ASSERT` and `ASSERTNOT` commands?

**Comment by francoisthire** [comment]
The tutorial obviously needs to be reworked, but I am not sure it will be done soon.

To answer to your first question, the sentence

> There is no term of type Istrue False and tt is the only term of type Istrue True.

Means that "at the point of the file", there is no term which inhabit the type "Istrue False". Of course, if you want to add one, you can but it was not intended here.

Actually your question is quite independent of dependent types. If I have a type "A" in Dedukti, I can always add an inhabitant of "A" with a declaration such as:

```dedukti
h : A
```

However, when we say that a type "A" as no inhabitant, we actually mean that we cannot **define** a constant of type "A" without adding further declarations. In other words, you cannot replace the dots in
```
def h : A := ...
```

**Comment by rprimet** [comment]
Thanks for your answer! Not sure I'm following everything though, the gist of my question was "since we can use this trick to check that a boolean is `True`, is it possible to use it to check that a boolean is `False` and if so, how ?"

**Comment by francoisthire** [comment]
Oh yes. You can do exactly the same trick using what you've posted before :

```dedukti
isFalse : Bool -> Type.

ff : isFalse False.
```

You can check by yourself =) .

Le mar. 28 mai 2019 à 15:37, Romain Primet <notifications@github.com> a
écrit :

**Comment by FranckS** [comment]
I'm not sure that's necessary, but I just wanted to add some explanation on the general idea behind this technique. I'm going to over-simplify a bit, so please excuse my approximations (and of course, fell free to correct, complete, and add pointers to what I write to help Romain digest this new stuff!)
On the line :
`def test1 : Istrue (equal (mult 10 10) 100) := tt.`
we build an inhabitant of `isTrue (equal (mult 10 10) 100)`, which we define by using `tt`, which has previously been declared as an inhabitant of `isTrue True`. Therefore, the typechecker will only accept this definition if it can unify `(equal (mult 10 10) 100)` and `True`, which is precisely why it's called "testing by typechecking" : if the typechecker succeeds to unify `(equal (mult 10 10) 100)` and `True`, then the test is ok because it's precisely what we want.

##### [Just a side note that you can skip]
Just for your information and to give you more hint on what's going on here, a more conventional variant of this kind of "test by typeching" in proof assistant (like Coq), is to use the (polymorphic) propositional equality `Eq` (of type `A -> A -> Prop`) which is a type with only one constructor called `Refl`, itself of type `Eq a a` for any a:A). The idea behind such a type is that you can only build (in an empty context) an equality proof between two things that are judgmentally equal (i.e. two things that compute to the same value). The reason is that you can only build an inhabitant of `Eq x y` when `x` and `y` "compute to the same thing", because the only constructor `Refl` that we have in our hands requires it by law.
Therefore, in the case of the previous example, an alternative could be to express it as :
`def test2 : Eq (mult 10 10) 100 := Refl.`
And the idea is, again, that the typechecker will accept this definition only if it can unify `mult 10 10` and 100.
The reason why we don't do this kind of test using a propositional equality (Eq) in Dedukti is that we do not have a (direct) support for polymorphism in the type theory behind Dedukti.
#####

Now, a word about falseness :
As @francoisthire explained, if you want to "test by typechecking" that something is false (in the sense that it computes to the boolean `False`, not to be confused with being provably false which has little to do with that), you need to have a way to express that a boolean expression computes to the value `False`. It is clearly cleaner to do as @francoisthire suggested (with a new symbol `isFalse` of type `Bool -> Type` and a new unique "constructor" called for instance `ff`, of type `isFalse False`), but please note that the other way you suggested (re-using `isTrue` and adding a second "constructor" to it) would work too! In fact, **all you need is a constructor indexed over the value `False` in order to let the typechecker do the verification work** by trying to unify your thing (that you hope evaluates to `False`) and the boolean `False` itself. However, it would look weird to still continue to call it "isTrue" after that, since it would now express being true or being false. But it's just a matter of naming, and you could rename it :
```
IsTrueOrFalse : Bool -> Type.
tt : IsTrueOrFalse True.
ff : IsTrueOrFalse False.
```
With this second approach, when you want to make sure that something evaluates to `False`, you would just use the constructor `ff`, and if the typechecker is happy, then you're all good (because you know `ff` builds a term indexed over the value `False`).
I still prefer to separate `isTrue` and `isFalse`, as it avoids mistakes in the *test* itself : if you use the `IsTrueOrFalse` version (with two constructors, one for True and one for False), you can screw up your test by using the other constructor and in fact expressing exactly the opposite of what you wanted. That's why I would avoid to do it : introducing slippery things in our specs and tests is not a good idea in general !

If any of the stuff I've mentioned here is not clear, do not hesitate to ask us more about that @rprimet !

**Comment by francoisthire** [comment]
Do you wanna rewrite the tutorial @FranckS ?

**Comment by FranckS** [comment]
Yeah I can try to rework some sections and to make it more friendly for people discovering the logical-farmulae-as-type principle and things related to dependent types. I'll see what I can do!

**Comment by rprimet** [comment]
Thanks for the additional info!

**Comment by francoisthire** [comment]
@FranckS If you plan to rework the tutorial, I invite you to open a PR. Meanwhile, I am closing this issue.
