### ISSUE TITLE
[Warning] Ignoring type declaration in rule context

### ISSUE THREAD

**Issue by rprimet** [Deducteam/Dedukti#164]
The Dedukti tutorial contains statements like this:

```
def append : List -> List -> List.
[ l2 : List ] append Nil l2 --> l2
[ a : A, l1 : List, l2 : List ] append (Cons a l1) l2 --> Cons a (append l1 l2).

```
Running `dkcheck` on this code will result in a warning:

`[Warning] Ignoring type declaration in rule context.`

Which suggests one question and one observation:

- If type declarations in rules raise a warning, why are they included in the tutorial? Are those good or bad practice?

- It would be really helpful to have line and column information attached to those warnings.

**Comment by francoisthire** [comment]
Tutorial is not up to date with the last version of Dedukti.

Types annotations were removed because they were not considered at all by
the parser and was just ignored.

We will try to fix that by the end of the week as well as your suggestion,
thanks for the report.

Le mer. 24 avr. 2019 à 13:12, Romain Primet <notifications@github.com> a
écrit :
