### ISSUE TITLE
Bracket checking too restrictive and obscure

### ISSUE THREAD

**Issue by Gaspi** [Deducteam/Dedukti#22]
Brackets are replaced with fresh unapplied "a la Miller" variables together with the promise of a systematic conversion check before the rule is fired.

For instance the rule
```[s1, s2, a, b] Term {rule s1 s2} (prod s1 s2 a b) --> x : Term s1 a -> Term s2 (b x).```
is interpreted as 
```[?_1, s1, s2, a, b] Term ?_1 (prod s1 s2 a b) --> x : Term s1 a -> Term s2 (b x).```
together with the promise that the rule is only applied when `?_1` is convertible with `rule s1 s2`.

A couple of sanity checks are performed when type checking the rule:
- The bracketed term should not use the locally bounded variables since it corresponds to *unapplied* variable from the context.
- Same for its type.
- The type inferred for the fresh variable in place of the bracket cannot depend on context variable occurring after the bracket. It seems reasonable to expect the bracketed term to have a type respecting this property as well.

(Potential) issues:
- For now the checks seem too restrictive. The term in brackets cannot depend on context variable declared after it in the rule context. Is there a reason for that ?
- Are the checks necessary ? Do we fail later on anyway if they are omitted ?
- Error messages could be more explicit. Make the distinction between all three reasons to fail.
- Should we fail or simply warn the user ? It could be that the user somehow "knows better" and indeed expects a term depending variables it's not supposed to.

**Comment by fblanqui** [comment]
For the record, let me recall Ronan's mail of December 1st on this topic:

---

En général, les brackets ne sont pas nécessaires.
Ainsi ta règle ci-dessous est a priori valide telle quelle.*
*[s1, s2, a, b] Term *_* (prod s1 s2 a b) --> x : Term s1 a -> Term s2 
(b x).
Et c'est bien le même raisonnement que pour les patterns inaccessibles 
de Agda qui justifie cela.

En fait les brackets sont une feature historique de Dedukti.
A l’époque où il n'y avait pas de patterns non lineaires dans Dedukti on 
ne pouvait pas écrire (declaration des symboles à la fin du mail)
head n (vcons n e l) --> e
pour récupérer le premier élément d'un vecteur de taille n. Donc on écrivait
head n (vcons {n} e l) --> e
Ça voulait dire que Dedukti typait la règle non linéaire mais ajoutait 
dans le contexte la règle linéarisée
head n1 (vcons n2 e l) --> e
Ça permettait évidement d'ajouter des règles qui cassaient complètement 
le typage puisque la règle ajoutée n’était pas le règle typée.
J'ai donc ajouté une vérification 'runtime' qui permet de détecter que 
les règles avec brackets sont utilisées de façon 'honnête'.
Si le test de conversion échoue, Dedukti crashe explicitement.
Maintenant qu'on a des règles non linéaires et surtout la détection de 
patterns inaccessibles, cette feature est moins utile mais elle n'a pas 
disparue car il reste au moins un cas d'utilisation.

Prenons la règle
tail n1 (vcons n2 e l) --> l
On pourrait penser qu'elle est bien typée car toute instance bien typée 
du membre gauche vérifie vec (S n1) ~ vec (S n2)
d’où on voudrait déduire n1 ~ n2 et vec n1 (le type du membre gauche) ~ 
vec n2 (le type du membre droit).
Mais cela ne marche que si vec (S n1) ~ vec (S n2) implique vec n1 ~ vec 
n2, ce qui est faux en général si je peux ajouter des règle de 
réécriture sur S ou vec.
Donc, dans le cas ou vec serait déclaré comme symbole définissable, la 
règle ne sera pas acceptée.

Par contre, il se peut que l'utilisateur n'ait pas l'intention d'ajouter 
de règle sur vec et S qui invaliderait vec (S n1) ~ vec (S n2) => vec n1 
~ vec n2
Dans ce cas on peut contourner le problème et utiliser les brackets
tail n (vcons {n} e l) --> l
comme au bon vieux temps.

vec: int -> Type.
E: Type.
vcons: n:int -> E -> vec n -> vec (S n).
head: n:int -> vec (S n) -> E.
tail: n:int -> vec(S n) -> vec n.

---

This also raises a number of questions/remarks:

1. From Ronan's mail, I understand that brackets are almost not 
necessary anymore and could perhaps be removed. So, it would be nice to 
make a list of rules that really need this feature.

2. What is the operational semantics of non-linear rules? Does Dedukti 
check syntactic equality or equality modulo beta+rewriting?

Checking for syntactic equality is sufficient and more efficient. So, if 
equality modulo is used, I propose to replace it by syntactic equality 
(which can be done in constant time when using sharing).

3. Bracquets have been introduced to help prove subject reduction. I 
think that subject reduction should be treated separately like 
confluence or termination.

4. Brackets introduce a form of conditional rewriting in Dedukti: f l 
{m} -> r applies to f t u if there is a substitution \sigma for the 
variables of l such that t = l\sigma and u is equivalent modulo 
beta+rewriting to m\sigma. However, in addition, if u is not equivalent 
to m\sigma, then an error is raised. Because of this potential failure, 
it is not usual conditional rewriting. The failure is introduced to 
check subject reduction at runtime! while it should be done statically. 
Removing this failure would also provide true conditional rewriting. 
Moreover, can't we replace equality modulo by syntactic equality? Aren't 
the two equationnaly equivalent when one is confluent?

Le 24/01/2018 à 19:29, Gaspard Férey a écrit :
>
> Brackets are replaced with fresh unapplied "a la Miller" variables 
> together with the promise of a systematic conversion check before the 
> rule is fired.
>
> For instance the rule
> |[s1, s2, a, b] Term {rule s1 s2} (prod s1 s2 a b) --> x : Term s1 a 
> -> Term s2 (b x).|
> is interpreted as
> |[?_1, s1, s2, a, b] Term ?_1 (prod s1 s2 a b) --> x : Term s1 a -> 
> Term s2 (b x).|
> together with the promise that the rule is only applied when |?_1| is 
> convertible with |rule s1 s2|.
>
> A couple of sanity checks are performed when type checking the rule:
>
>   * The bracketed term should not use the locally bounded variables
>     since it corresponds to /unapplied/ variable from the context.
>   * Same for its type.
>   * The type inferred for the fresh variable in place of the bracket
>     cannot depend on context variable occurring after the bracket. It
>     seems reasonable to expect the bracketed term to have a type
>     respecting this property as well.
>
> (Potential) issues:
>
>   * For now the checks seem too restrictive. The term in brackets
>     cannot depend on context variable declared after it in the rule
>     context. Is there a reason for that ?
>   * Are the checks necessary ? Do we fail later on anyway if they are
>     omitted ?
>   * Error messages could be more explicit. Make the distinction
>     between all three reasons to fail.
>   * Should we fail or simply warn the user ? It could be that the user
>     somehow "knows better" and indeed expects a term depending
>     variables it's not supposed to.
>
>
After 1, is it really worth to consider all these questions without 
knowing whether brackets are really necessary?

**Comment by Gaspi** [comment]
**Item 2)** Dedukti handles non left linearity with checks for convertibility modulo (beta / gamma) rewriting. A syntactic check is still performed before reducing (just in case).
I don't see why syntactic equality would be sufficient here. Certainly `eq 1 (S 0)` should match the rule `[x] eq x x --> true.`.

**Item 4)** I agree it's close but I believe practical conditional rewriting should also handle more general conditions than the ones generated by brackets (which are always of the form `X ~ term(Y,Z,...)` where X, Y, Z, ... variables in the context). For instance one could want to express `f(X) ~ g(Y)` or `predicate(X,Y,Z) ~ true`. This question probably deserve it's own issue as it's a whole new line of development.

**Item 1)** I agree that brackets have become a rare sight in practice and that it probably is for the best.
I only see two potential use cases:
1. In the following example
```
A : Type.

T : A -> Type.
def t : x:A -> T x.

U : x:A -> T x -> Type.
u : x:A -> y : T x -> U x y.

def f : x:A -> y:T x -> U x y.
[] f a {t a} --> u a (t a).
```
- the bracket is necessary to type check the rule since the pattern has type `U a ?_` while the right hand side has type `U a (t a)` (where `?_` is the fresh variable replacing the bracket).
- Besides in that case this can't be replaced with an inaccessible pattern since Dedukti has no way of inferring that the only way to produce a term of type `T a` is with `t a` (because it might not be the case). The user "knows better" and gives Dedukti the guarantees to type check the rule.
- A reason why one would not want to simply write `[] f a (t a) --> u a (t a).` is that, `t` being definable, the user really want the second argument of `f`to be "something convertible with `t a`" and not necessarily `t a` itself. In particular if `T a` is a product type, `t a` might reduce to a lambda term.

2. In a similar way
```
A : Type.
Pair : Type.
def pair : A -> A -> Pair.

def fst : Pair -> A.
[a] fst (pair a _) --> a.
def snd : Pair -> A.
[b] snd (pair _ b) --> b.

T : A -> Type.
t : x:A -> T x.

def U : Pair -> Type.
[x,y] U (pair x y) --> A.

def f : x:Pair -> T (fst x) -> T (snd x) -> U x.
[x,y] f {pair x y) (t x) (t y) --> x.
```
- The rule requires `U ?_ ~ A` which is satisfiable when `?_` is a pair, hence the bracket is required to typecheck the rule.
- Here again the user "knows" that the typing constraints (`x ~ fst ?_` and `y ~ snd ?_`) are only satisfiable when `?_` is actually `pair x y` and wants to communicate this information to help the type checker with this rule.
- Note: this example should not type check (yet) since the bracket term depends on context variables occurring later in the pattern. I believe this should be accepted as long as the *type* of the bracket doesn't depend on these variables.

**Comment by rafoo** [comment]
> brackets are almost not necessary anymore and could perhaps be removed.

I see two advantages about brackets compared to patterns:
1. they are not restricted to a fragment of the syntax of terms,
2. two convertible bracket terms have the same semantics.

Point (1.) might be useful if we need to do beyond the syntactic limitations of Miller patterns. As a consequence of (2.), brackets can be used when some part of a rewrite rule would be harder to give in normal form.

For example, in dklib, the type of characters is defined to be `dk_machine_int.Mint (dk_nat.S (dk_nat.S (dk_nat.S (dk_nat.S (dk_nat.S (dk_nat.S (dk_nat.S dk_nat.O)))))))` (i.e. a 7-bit number); if we want to define for example the `tail` function of type `list char -> list char` on lists of chars without brackets, we have to provide the normal form of the type: 

`[tl] tail (cons (dk_machine_int.Mint (dk_nat.S (dk_nat.S (dk_nat.S (dk_nat.S (dk_nat.S (dk_nat.S (dk_nat.S dk_nat.O)))))))) _ tl) --> tl.`

However, with brackets we can simply define `tail` by `[tl] tail (cons {char} _ tl) --> tl.`

> Bracquets have been introduced to help prove subject reduction

On the contrary, when brackets were introduced, they could precisely be used to break subject reduction. It was not about proving anything, it was about circumventing the lack of non-linearity.

**Comment by fblanqui** [comment]
Le 25/01/2018 à 13:32, Gaspard Férey a écrit :

> *Item 1)* I agree that brackets have become a rare sight in practice 
> and that it probably is for the best.
> I only see two potential use cases:
>
>  1. In the following example
>
> |A : Type. T : A -> Type. def t : x:A -> T x. U : x:A -> T x -> Type. u 
> : x:A -> y : T x -> U x y. def f : x:A -> y:T x -> U x y. [] f a {t a} 
> --> u a (t a). |
>
>   * the bracket is necessary to type check the rule since the pattern
>     has type |U a ?_| while the right hand side has type |U a (t a)|
>     (where |?_| is the fresh variable replacing the bracket).
>
Are you sure? If we replace {t a} by y, we get the problem U a (t a) ~?~ 
U a y. Since U is a constant, y ~ t a.

>   * Besides in that case this can't be replaced with an inaccessible
>     pattern since Dedukti has no way of inferring that the only way to
>     produce a term of type |T a| is with |t a| (because it might not
>     be the case). The user "knows better" and gives Dedukti the
>     guarantees to type check the rule.
>   * A reason why one would not want to simply write |[] f a (t a) -->
>     u a (t a).| is that, |t| being definable, the user really want the
>     second argument of |f|to be "something convertible with |t a|" and
>     not necessarily |t a| itself. In particular if |T a| is a product
>     type, |t a| might reduce to a lambda term.
>
>  2. In a similar way
>
> |A : Type. Pair : Type. def pair : A -> A -> Pair. def fst : Pair -> A. 
> [a] fst (pair a _) --> a. def snd : Pair -> A. [b] snd (pair _ b) --> 
> b. T : A -> Type. t : x:A -> T x. def U : Pair -> Type. [x,y] U (pair 
> x y) --> A. def f : x:Pair -> T (fst x) -> T (snd x) -> U x. [x,y] f 
> {pair x y) (t x) (t y) --> x. |
>
>   * The rule requires |U ?_ ~ A| which is satisfiable when |?_| is a
>     pair, hence the bracket is required to typecheck the rule.
>
Indeed, here, if we replace {pair x y} by z, we end with the problem U z 
~?~ A with x ~ fst z and y ~ snd z. To conclude, we would need 
surjective pairing (eta/unicity for pairs): z ~ pair (fst z) (snd z), 
which can be done by adding the non-linear rule pair (fst z) (snd z) --> 
z. Another simpler and more efficient solution is to replace U (pair x 
y) --> A by U z --> A.

Now, what is the semantics of |f {pair x y} (t x) (t y) --> x? f a b c 
will be reduced if b = t b', t = t c' and a ~ pair b' c'. Since pair is 
constant, we have a -->* pair b'' c'', b' -->* b'' and c' -->* c''. So, 
we could as well take f {pair _ _} (t x) (t y) --> x. Indeed, by taking 
{pair x' y'} for {pair _ _}, we get U (pair x' y') ~ A (and also x ~ fst 
(pair x' y') ~ x' and y ~ snd (pair x' y') ~ y').

Question: is it an example taken from a Dedukti library or an example 
specially cooked up?

|

**Comment by fblanqui** [comment]
Le 25/01/2018 à 20:56, Raphaël Cauderlier a écrit :
>
>     brackets are almost not necessary anymore and could perhaps be
>     removed.
>
> I see two advantages about brackets compared to patterns:
>
>  1. they are not restricted to a fragment of the syntax of terms,
>  2. two convertible bracket terms have the same semantics.
>
> Point (1.) might be useful if we need to do beyond the syntactic 
> limitations of Miller patterns. As a consequence of (2.), brackets can 
> be used when some part of a rewrite rule would be harder to give in 
> normal form.
>
> For example, in dklib, the type of characters is defined to be 
> |dk_machine_int.Mint (dk_nat.S (dk_nat.S (dk_nat.S (dk_nat.S (dk_nat.S 
> (dk_nat.S (dk_nat.S dk_nat.O)))))))| (i.e. a 7-bit number); if we want 
> to define for example the |tail| function of type |list char -> list 
> char| on lists of chars without brackets, we have to provide the 
> normal form of the type:
>
> |[tl] tail (cons (dk_machine_int.Mint (dk_nat.S (dk_nat.S (dk_nat.S 
> (dk_nat.S (dk_nat.S (dk_nat.S (dk_nat.S dk_nat.O)))))))) _ tl) --> tl.|
>
> However, with brackets we can simply define |tail| by |[tl] tail (cons 
> {char} _ tl) --> tl.|
>
|I don't understand your example. What is the type of cons and tail? Why 
can't we use char in the first place? Why do we need to put anything at 
all? Thanks for elaborating here.

|
