### ISSUE TITLE
' not allowed at the beginning of an identifier

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/Dedukti#328]
https://github.com/Deducteam/Dedukti/blob/3dbbffdb5c8af3be15bb2c7a59ba263505c3a360/parsing/lexer.mll#L25

it may be useful to write 'a like in ML and systems based on ML (Isabelle, HOL-Light, HOL4)

**Comment by GuillaumeGen** [comment]
It clearly is possible and easy (you pointed the line to change).
Hence the question is do we want to do it.

Benefits : `'a` becomes a valid identifier, allowing us to have code closer to Ocaml naming convention.
Drawbacks : we lose the ability to have a native type of characters with the `'a'` syntax.

Since I see the point for translation to have a more idiomatic syntax and I hardly see someone adding a native type of characters in Dedukti, I am in favor of this change.
