### ISSUE TITLE
Ambiguity in rule context

### ISSUE THREAD

**Issue by Gaspi** [Deducteam/Dedukti#4]
When defining a rewrite rule, Dedukti's parsing uses the given "context" only to tell apart defined constant identifier from variables in the pre-pattern (since it can't access the signature).
Pattern is then built from reading the term and adding variable to the context as we encounter them.

Issues:
- the (facultatively) **given types are completely ignored** when type checking the rule (they can even be incorrect types). We could:
    - remove the possibility to write `[v1 : T1, v2 : T2] ...`. Warning: this will raise some retro-compatibility issues.
    - consider these types as constraints on the types inferred for the corresponding variables (just like brackets) and check them during rule type checking.
- the list of identifiers in the given context is to be simply considered as a set of names (potentially) corresponding to variables. Their order is not the order of variables in the actual context, it doesn't really matter whether variable names are used or not, fresh (unapplied) extra variables are silently added to replace wildcards (jokers).
    - This behavior should be made clear in the documentation / tutorial. It is for instance misleading to refer to this list as "the context" of the rewrite rule.
    - We should probably simply ignore unused variables instead of warning about them.
    - Ideally, we should be able to drop the declaration of variable names at parsing and infer in the kernel which symbol is from the signature and which is a context variable.

**Comment by francoisthire** [comment]
> the (facultatively) given types are completely ignored when type checking the rule (they can even be incorrect types). We could:
> 
>     remove the possibility to write [v1 : T1, v2 : T2] .... Warning: this will raise some retro-compatibility issues.

But this is helpful sometimes to read rewrite rules. It is more like comments to help the user to read the code. I am agree though that this might be misleading.

> consider these types as constraints on the types inferred for the corresponding variables (just like brackets) and check them during rule type checking.

It is a bit different from brackets because brackets are checked dynamically also (using constraints). If my understanding is correct, you want that these types behave like type annotations in OCaml?

> This behavior should be made clear in the documentation/tutorial. It is for instance misleading to refer to this list as "the context" of the rewrite rule.

Yup, this is related to issue #3.

> Ideally, we should be able to drop the declaration of variable names at parsing and infer in the kernel which symbol is from the signature and which is a context variable.

That is not a problem for the kernel, right? It is more a scoping problem I think. With the actual behavior of modules, it is possible since a constant can always be fully qualified. But one more time, it might help a lot the reading of a rewrite rule to have a local context.  So a solution might be that the local context is optional?

**Comment by GuillaumeGen** [comment]
> We should probably simply ignore unused variables instead of warning about them.
I think that you meant the contrary. Now, we are simply ignoring unused variables and it would be better to warn the user about it, since it is probably a mistake (normally, you don't write the rule [x,y,z] f 0 --> 0, it is not natural at all).

**Comment by francoisthire** [comment]
Right now, the behavior is to generate a warning. We should open a new issue if we want to change the behavior.
