### ISSUE TITLE
Underscore is never parsed as an identifier

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/Dedukti#40]
Line 23 of the parser we can find 
```
let ident   = ['a'-'z' 'A'-'Z' '0'-'9' '_']['a'-'z' 'A'-'Z' '0'-'9' '_' '!' '?' '\'' ]*
```
so `_` is a valid identifier according this regexp. However, because of line 44 that defines tokens : 
```
  | "_"         { UNDERSCORE ( get_loc lexbuf ) }
```
``_` is never parsed as an identifier. 

By the way, what is the reason that an identifier cannot start with a `?`, `!` ?

**Comment by rafoo** [comment]
I guess you are talking about lexing, not parsing. Distinguishing `_` from idents is necessary because both `_` and idents are valid patterns. However, we could specifically allow abstracting on `_` to define constant functions.

We could also use a different lexer for left-hand sides but I think it brings too much complexity with regard to the benefit of having `_` as an identifier.

I presume that `?` is forbidden as first character of idents to ensure that the names generated instead of `_` patterns do not clash with regular variables. I have no clue for `!`.

**Comment by francoisthire** [comment]
> I presume that ? is forbidden as first character of idents to ensure that the names generated instead of _ patterns do not clash with regular variables.

The module Basic defines two special identifiers that are `qmark` and `dmark`, the first one is an alias for `?` while the second is an alias for `$`. However, `$` is not allowed in the regexp for identifiers.

If one wants to avoid clashes, the best thing is probably to introduce identifiers that cannot be parsed as it is done with dmark I guess. 

Moreover, I know that identifiers generated with qmark can be printed and hence, cannot be parsed again.
