### ISSUE TITLE
Printing functions are written twice

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/Dedukti#45]
For example, to print a term, there is a function `pp_term` inside the module `Term` and a function `print_term` inside the module `Pp`. Probably one function is enough. What is the best choice to make here?

Most of the time, functions in Pp are just copy-paste code. Probably `Pp` should exist for the library, but probably it needs a little cleanup.

**Comment by rlepigre** [comment]
I think pp_term should remain in `Term`, where it could even be called `pp`, and accessed with `Term.pp`. I would even go further and remove the `Pp` module, which is completely useless.

**Comment by Gbury** [comment]
Generally, I'd say every type definition should always be almost immediately followed by at least the following functions: `hash : t -> int`, `compare : t -> t -> int`, `equal : t -> t -> bool`, and `print : Format.formatter -> t -> unit`, in which case the `Pp` module is indeed useless.

Concerning printing functions specifically, the standard `print` (or `pp` depending on your taste) defined together with each type, should output something human readable on a console (i.e. should at least use `Format`'s boxes and possible some escape codes to  put emphasis on what's important); whereas printing functions that are meant for defined format (such as DOT export, or exporting things in Coq Syntax), deserve their own module.

**Comment by francoisthire** [comment]
I agree that Pp is probably useless in that case.

**Comment by rlepigre** [comment]
Personally, I find the `Format` module really annoying, especially in exported functions. I would really rather export printing functions compatible with `Printf`, with type `out_channel -> 'a -> unit`. In any case, the only interest of `Format` is to print terms nicely, and it is otherwise useless.

**Comment by Gbury** [comment]
Having readable terms (particularly when they become big) is, at least in my opinion, a really, *really*, **really** important thing to have in a printing function, and `Format`'s boxes (particularly, the horizontal-vertical box) is a big help to move toward that. Just imagine a term of depth 10 (which happens quite often) printed with, and without indentation...

More generally, indentation is good (and often necessary to have actually readable output), and Format is currently the standard (and probably the only) good solution in OCaml. Additionally, I recall that I saw dedukti performing manual indentation in some outputs, and it seems really ugly compared to using Format so....

Note that if you completely drop the Format module, you could even provide functions that print on a buffer rather than an `out_channel`.

**Comment by rlepigre** [comment]
I was **not** suggesting that we stop using `Format`, just that we encapsulate the exported functions so that they can be used with `Printf`. Of course, we cannot do without proper formatting of terms.

**Comment by Gbury** [comment]
I'm not sure if that is possible or even desirable.
How would you encapsulate such functions ? I guess it would rely on some ugly bufferring (basically printing into a buffer/string using Format and then printing that back into an `out_channel`), which 1) is not really efficient for debug printing, 2) breaks compositionality of indentation (imagine you are printing a term from a context where you already have some indentation, then it would break everything).

Anyway, practically every project that I know of in OCaml uses Format already, so I don't really see your problem with using it.

**Comment by francoisthire** [comment]
But in our case, Pp is a pretty printer and the purpose of these functions is to print something that can be next parsed by the Dedukti parser while printing functions in each module are only there for debugging purposes. So maybe, we should keep the module Pp.

**Comment by Gbury** [comment]
In that case, indeed I agree that the `Pp` module should be kept (though maybe renamed to something more explicit such as `Export` to avoid confusion ? or at least document the intended use of each function/module).

**Comment by rlepigre** [comment]
Well, the important thing is that the printing function for the `entry` type is compatible with the parser. And this imply that every other function should be compatible with the parser. This should be documented in the interface of these functions when they are exported. There is no point in having an additional module just for that.

On `Format`, I don't care that much. But I it is really annoying to have to flush two buffers when printing.

**Comment by Gbury** [comment]
I kinda disagree with your first point. So here is a lenghty monologue that is more about API/library design:

I see at least two different printing usage that warrant two different implementations:
- export printing: the goal here is to print back structures that have a defined semantics in dedukti, and ensure that these printing functions and the parser are in sync
- debug printing: in that case, you might often want to 1) add some more information (because you need it for debugging) that is tied to the implementation (i.e. not part of the semantics/definition of the language) 2) change the syntax because it is more conveninent.

Additionally, you might want to print some internal data structures (decision trees, hashtables, substitutions, ...) that do not have a defined external semantics (or said differently, are not parsed), and integrate them to the debug output of larger structures that do have an external semantic that must be respected. For instance, one might imagine a debug output that consists in printing the typing environment (including rewrite rules, decision trees, etc..) before each `entry` (to check that nothing is missing/incorrect), and that clearly can't work with being compatible with the parser.

Basically, you absolutely need some kind of debug printing, and these functions need to be right next to the type definitions because they will very likely be used in all subsequent functions that might use the type. These function should be meant mainly for developer's eyes, and typically will be printed on a `tty` (and **not** a regular file), thus they can (and should) use all the features available (including indentation, colors, escape codes, unicode, etc..) to achieve the most readable output. Every data structure should have one debug function (because you'll always need to debug/print it at one point or another).

Then you might need to export back some of your data structures (and not all, since they might not all be relevant), in a given format (for instance in dedukti's own format, but it's actually a particular case), and in that case you'll likely need to define a new set of printing functions that are carefully crafted to respect the given syntax, so this means no ANSI escape codes, maybe some unicode depending on the definition of the language, it might require some mutable globale state (for instance in dedukti to remember relative to which module paths/identifiers are printed), which make it really hard to share implementation with the debug functions (particularly the global mutable state). These functions have no real need to be next to the type definitions, and moreover should be updated together to ensure that the syntax is respected, so it makes sense to bundle them in their own module (such as `Export_to_syntax`).

Anyway, that's my reasoning and point of view, feel free to tell me if you disagree.

Lastly, what's that about flushing two buffers when using `Format` ?

**Comment by rafoo** [comment]
In my opinion, the choice between putting something in or outside the kernel should be a matter of trust so if we have an opportunity to avoid depending on Format and/or Printf, we should probably take it.

Currently the two pretty printers (the Term one and the Pp one) are not so close and the Pp one is way better:
- Term.pp_term uses the Format module but uses it as if it were Printf (no box, no break, totally unreadable),
- Term.pp_term prints DeBrujin indices whereas Pp.print_term renames variables when it sees a clash,
- Term.pp_term always qualifies local constants, Pp.print_term does not, 
- The type `A -> B` is printed as `A -> B` by Pp.print_term but as `? : A -> B` by Term.pp_term, this is annoying when comparing complicated types,
- the only advantage of Term.pp_term is that its DB printing is unambiguous whereas I am not sure that Pp.print_term is able to see variables clashing with constants but even this can be solved in Pp.print_term by setting Pp.print_db_enabled to true (I think this used to be an option of `dkcheck`).

So I think we should keep Pp, push it outside of the kernel together with the Errors module and remove everything related to pretty-printing (or not-so-pretty printing for that matter) from the kernel.

**Comment by rafoo** [comment]
I have looked a bit at this issue, we cannot always postpone printing by raising exceptions because the kernel printing functions are also used to print warning messages.

**Comment by francoisthire** [comment]
Fixed #106 .
