### ISSUE TITLE
Representation of rules and patterns in Dedukti

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/Dedukti#63]
The whole project contains three representations of rules and patterns in Dedukti. Probably some representations are not needed and are cumbersome. Moreover, the translation chain between these representations makes things complicated for the type checker. It should be interesting to clean up a little bit these things.

1) The rules where the LHS is not a Miller's pattern should be rejected at the scoping level.

2) Non-linear rules where the LHS does not check the arity criterion (see #60) should be also rejected at the scoping level.

3) The types  `wf_pattern` and `pattern` should be merged. Maybe we should keep the type `wf_pattern` representation.

4) The type `'a rule` should be removed and only the type `rule_infos` should be used.

**Comment by Gaspi** [comment]
I agree that the chain of successive rule representations is a bit long:
prepattern (parsing) -> untyped pattern (scoping) -> wf_pattern (rule) -> typed_rule (typing).

Well-formed (WF) patterns are needed because of the implicit pattern transformation in Dedukti.
When the user defines the following rule
```[b,c,a : Nat] f a _ (x => b x) {a + b} a --> t.```
it is transformed into a representation looking like this
`[a,#1,b,#2,#3] f a #1 (x => b x) #2 #3 --> t.` when `#3 ~ a` always `#2 ~ a + b`
where:
- `#1` is a fresh variable introduced for the joker
- `#2` is a fresh variable introduced for the bracket
- `#3` is a fresh variable introduced for non linear variable `a`
- Bracket and Linearity constraints are generated
- Unused context variable are ignored
- Context types are ignored 
- Context is reordered

The user doesn't directly write well-formed patterns, they are generated from their input.
The kernel should not handle this transformation which could be interface-dependent. It should only care about the generated well formed linear "à la Miller" pattern and its constraints.

- (1./2.) The kernel has to check the patterns it receives (well-typedness but also well-formedness) before adding them to the signature. Pattern well-formedness should not be checked twice (at scoping and in kernel). I suggest that when the pattern transformation described above fail then it's a scoping issue, otherwise we let the kernel raise the issue. Right now, most of the well-formedness is guaranteed by the representation type anyway.

- (3.) `pattern` should be handled by the scoper, maybe it should be merged with `prepattern`. The kernel should only know about `wf_pattern`, the scoper output.

- (4.) It seems reasonable that each different pattern representation is related to a different rule/context representation. Because of its DeBruijn representation the kernel's representation only needs a context size (neither type, not location nor even names for context variables). We might still want to keep a variable name context for pretty-printing and debugging.
