### ISSUE TITLE
Rewrite engine and Signature

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/Dedukti#94]
The rewrite engine is a little bit dependent on the signature. For example, if you ask the rewrite engine to reduce the definition of `test` in the following example:

```
[] one --> S 0.

def test := x : nat => one.
```
it fails because `nat` doesn't have a Decision Tree in the signature (it is not the case if you remove the variable `x`). I think however that this is a silly reason for failing. Since we are not using typing information during the reduction. I have the impression that if no decision tree is associated with a symbol, the rewrite engine could go on.

This problem arises only when you use the rewrite engine without the type checker. The only way to do that right now is to use Dedukti as a library.

**Comment by francoisthire** [comment]
Reduction.reduction

**Comment by Gaspi** [comment]
I believe `get_dtree` can only fail for two reasons:
- symbol is not in the signature
- rules for the symbol don't allow to compute a decision tree (ill-formed)

If I'm guessing correctly, your stack trace looks as follow:
```
Reduction.snf test    (has to be snf strategy otherwise
                       the type annotation 'nat' wouldn't be reduced)
Reduction.whnf nat
Reduction.state_whnf
Signature.get_dtree
Signature.get_infos
-> SignatureError (SymbolNotFound _) raised
```
which I think is the expected behavior. All symbols must be declared and added into the signature before doing anything with them.

I don't think this restriction prevents from playing with the reduction engine while ignoring typing. You just need to declare `nat` in the signature.

**Comment by francoisthire** [comment]
See #
