### ISSUE TITLE
Extending patterns

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/Dedukti#97]
At FSCD 2016, Tomer Libal and Dale Miller propose an [extension](https://hal.inria.fr/hal-01379683/document) for patterns.

This extension allows to write this rewrite rule for example (if my understanding of their criterion is correct):
```
[F] foo (x => F (S x)) --> 0.
```

that is currently rejected by Dedukti. 

As far as I know, I don't know any need to extend patterns with this criterion. However, I am curious, and I was wondering how hard it would be to extend the matching algorithm with this new criterion.

Do you have any remarks @rafoo  @Gaspi @GuillaumeGen @rlepigre ?

**Comment by rlepigre** [comment]
If I understand correctly, this means that Miller variables can be applied to (static) constructors under matched higher-order variables?

In `lambdapi` syntax, this would give the following (for example), which is currently rejected (I'm not sure why), but it would trigger an error during reduction (or maybe not pass some final check, but I cannot verify due to the previously mentioned error).
```
foo (x => ?F[S x]) --> ?F[0].
```
I think that we could the system rather easily to handle such cases, but would that really be useful? We already do not use Miller patterns that much, and handling such case may cause efficiency losses.

**Comment by rafoo** [comment]
I haven't read the paper yet but this generalization of higher-order patterns might improve my constructivization heuristic (https://dblp.org/rec/html/conf/lfmtp/Cauderlier16).

**Comment by francoisthire** [comment]
This won't be implemented since it is not needed.
